<!--Generated by ::xox::SimpleXmlNodeWriter bthomass at Thu Jul 12 14:35:18 EDT 2007-->
<!DOCTYPE xounit:TestSuiteContinuous [
<!ELEMENT xounit:TestSuiteContinuous (apiDoc*,delay*,location*,name*,packages*,results*,styleSheet*,textFormatter*,times*,title*,url*,webPath*,xoexception:test:TestThrowable*,xoexception:test:TestProcTry*) >
<!ELEMENT apiDoc (#PCDATA) >
<!ELEMENT delay (#PCDATA) >
<!ELEMENT location (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT packages (#PCDATA) >
<!ELEMENT results (#PCDATA) >
<!ELEMENT styleSheet (#PCDATA) >
<!ELEMENT textFormatter (#PCDATA) >
<!ELEMENT times (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT url (#PCDATA) >
<!ELEMENT webPath (#PCDATA) >
<!ELEMENT xoexception:test:TestThrowable (currentTestMethod*,result*) >
<!ELEMENT currentTestMethod (#PCDATA) >
<!ELEMENT result (#PCDATA) >
<!ELEMENT xoexception:test:TestProcTry (currentTestMethod*,result*) >
] >

<xounit:TestSuiteContinuous>
    <apiDoc>http://xotcllib.sourceforge.net/xodoc/</apiDoc>
    <delay>30</delay>
    <location>/var/www/html/xoexception/</location>
    <name>xoexception Unit Tests</name>
    <packages>xoexception</packages>
    <styleSheet>style.css</styleSheet>
    <times>1</times>
    <title>xoexception Continuous Testing</title>
    <url>http://xotcllib.sourceforge.net</url>
    <webPath>http://neat3/xoexception/</webPath>
    <xoexception:test:TestThrowable/>
    <xoexception:test:TestProcTry/>
</xounit:TestSuiteContinuous>

