<!--Generated by ::xox::SimpleXmlNodeWriter bthomass at Tue Jul 10 21:03:13 EDT 2007-->
<!DOCTYPE xounit:TestSuiteContinuous [
<!ELEMENT xounit:TestSuiteContinuous (apiDoc*,delay*,location*,name*,packages*,results*,styleSheet*,textFormatter*,times*,title*,url*,webPath*,xox:test:TestParseArgs*,xox:test:TestEval*,xox:test:TestXmlReader*,xox:test:TestSpy*,xox:test:TestEnvironment*,xox:test:TestSimpleXmlNodeWriter*,xox:test:TestClassParameterArray*,xox:test:TestClass*,xox:test:TestReload*,xox:test:TestClassParameter*,xox:test:TestLogger*,xox:test:TestObjectGraph*,xox:test:TestGenerateVariable*,xox:test:TestXmlNodeReader*,xox:test:TestTuple*,xox:test:TestXmlNodeWriter*,xox:test:TestPackage*,xox:test:TestDebugging*,xox:test:TestTemplate*,xox:test:TestXmlNodeSchemaWriter*,xox:test:TestNode*,xox:test:TestHigherOrderTcl*,xox:test:TestTrace*,xox:test:TestObject*) >
<!ELEMENT apiDoc (#PCDATA) >
<!ELEMENT delay (#PCDATA) >
<!ELEMENT location (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT packages (#PCDATA) >
<!ELEMENT styleSheet (#PCDATA) >
<!ELEMENT textFormatter (#PCDATA) >
<!ELEMENT times (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT url (#PCDATA) >
<!ELEMENT webPath (#PCDATA) >
<!ELEMENT xox:test:TestParseArgs (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestEval (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestXmlReader (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestSpy (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestEnvironment (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestSimpleXmlNodeWriter (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestClassParameterArray (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestClass (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestReload (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestClassParameter (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestLogger (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestObjectGraph (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestGenerateVariable (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestXmlNodeReader (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestTuple (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestXmlNodeWriter (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestPackage (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestDebugging (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestTemplate (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestXmlNodeSchemaWriter (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestNode (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestHigherOrderTcl (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestTrace (currentTestMethod*,result*) >
<!ELEMENT xox:test:TestObject (currentTestMethod*,result*) >
] >

<xounit:TestSuiteContinuous>
    <apiDoc>http://xotcllib.sourceforge.net/xodoc/</apiDoc>
    <delay>30</delay>
    <location>/var/www/html/xox/</location>
    <name>xox Unit Tests</name>
    <packages>xox</packages>
    <styleSheet>style.css</styleSheet>
    <times>-1</times>
    <title>xox Continuous Testing</title>
    <url>http://xotcllib.sourceforge.net</url>
    <webPath>http://rtp-xdm-001/xox/</webPath>
    <xox:test:TestParseArgs/>
    <xox:test:TestEval/>
    <xox:test:TestXmlReader/>
    <xox:test:TestSpy/>
    <xox:test:TestEnvironment/>
    <xox:test:TestSimpleXmlNodeWriter/>
    <xox:test:TestClassParameterArray/>
    <xox:test:TestClass/>
    <xox:test:TestReload/>
    <xox:test:TestClassParameter/>
    <xox:test:TestLogger/>
    <xox:test:TestObjectGraph/>
    <xox:test:TestGenerateVariable/>
    <xox:test:TestXmlNodeReader/>
    <xox:test:TestTuple/>
    <xox:test:TestXmlNodeWriter/>
    <xox:test:TestPackage/>
    <xox:test:TestDebugging/>
    <xox:test:TestTemplate/>
    <xox:test:TestXmlNodeSchemaWriter/>
    <xox:test:TestNode/>
    <xox:test:TestHigherOrderTcl/>
    <xox:test:TestTrace/>
    <xox:test:TestObject/>
</xounit:TestSuiteContinuous>

